SELECT
    kcu.CONSTRAINT_NAME,
    kcu.TABLE_NAME,
    kcu.COLUMN_NAME,
    kcu.REFERENCED_TABLE_NAME,
    kcu.REFERENCED_COLUMN_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu
        JOIN
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc
    ON kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
WHERE
        kcu.TABLE_SCHEMA = 'nightbot_quiz' -- CHANGE ME
  AND tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY
    kcu.TABLE_NAME, kcu.COLUMN_NAME;
