name: Compile TypeScript and push to `dist`

on:
  push:
    branches:
      - dist-build-poc  # TODO fix me

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ref: dist-build-poc  # TODO fix me

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # npm install not needed because of the project's simple setup; uncomment if this is not the case in the future
      # - name: Install dependencies
      #  run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Copy files to root
        run: | 
          cp project/build.js build2.js
          cp project/generator.html generator2.html
          cp project/tables.js tables2.js

      - name: Switch to dist-test branch
        run: |
          git fetch origin dist-test
          git checkout -B dist-test

      - name: Move files back to project folder
        run: |
          mv build2.js build.js
          mv generator2.html generator.html
          mv tables2.js tables.js

      # TODO: remove
      - name: Git status
        run: git status

      # https://github.com/stefanzweifel/git-auto-commit-action
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: dist-test
          commit_message: Automated change (build TS)
          file_pattern: 'build.js generator.html tables.js'
