name: Compile TypeScript and Push to Dist

on:
  push:
    branches:
      - dist-build-poc  # TODO fix me

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # TODO : Step 3: Install dependencies -- needed?
      # - name: Install dependencies
      #  run: npm install

      # Step 4: Compile TypeScript to JavaScript
      - name: Compile TypeScript
        run: npm run build

# TODO: REplace dist-test with dist
      # Step 5: Push to `dist` branch
      - name: Push to `dist` branch
        run: |
          # Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin dist-test
          git checkout -B dist-test

          # Copy compiled files to root of the dist branch
          # rsync -a --delete dist-test/ ./

          # Add, commit, and push changes to `dist` branch
          git add .
          git commit -m "Build and deploy TypeScript to dist branch" || echo "No changes to commit"
          git push origin dist-test --force
